---
- name: Install DHCP server package
  package:
    name: "{{ dhcp_package_name }}"
    state: present
  become: true
  tags: dhcp_install

- name: Configure DHCP server
  template:
    src: dhcpd.conf.j2
    dest: "{{ dhcp_config_path }}"
    owner: root
    group: root
    mode: '0644'
    backup: true
  become: true
  notify: restart dhcpd
  tags: dhcp_config

- name: Start and enable DHCP server
  systemd:
    name: "{{ dhcp_service_name }}"
    state: started
    enabled: true
    daemon_reload: true
  become: true
  tags: dhcp_service
